config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  patch '/done/:id', to: 'tasks#done', as: :done_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	http_basic_authenticate_with name: "lincoln" , password: "1809"
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @task = Task.new
        @tasks = Task.all.order(created_at: :desc)
    end
     
    def create
       @task = Task.new(tasks_params)
       if @task.save
           redirect_to root_path
       else
           redirect_to root_path
       end
        
    end
# Удаление задачи    
def destroy
  @task = Task.find(params[:id])
  @task.destroy
 
  redirect_to root_path
end
#!!!!!!!!

#Данные загружаються в форму
def edit
    @task = Task.find(params[:id])
end
#!!!!!!!!

#Отвечает за обновление данных
def update
    @task = Task.find(params[:id])
 
    if @task.update(tasks_params)
        redirect_to root_path
    else
        redirect_to root_path
    end
end
#!!!!!!!!
#Обновление свойства 
def done
    @task = Task.find(params[:id])
     
    if(@task)
        @task.status = "true";
 
        redirect_to root_path if @task.save
    else
        redirect_to root_path
    end
end
#!!!!!!


    private
        def tasks_params
            params.require(:task).permit(:title, :text)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todonew</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">


      
<h1>Редактирование задачи</h1>





<%= form_for @task do |f| %>

    <%= f.label :title,"Название" %><br>

  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: "Название задачи" %>
  </div>


    <%= f.label :text, "Описание" %><br>
  <div class="form-group">
    <%= f.text_area :text, class: "form-control", size: "40x4", placeholder: "Описание" %>
  </div>

  
  <p>
   
    <%= f.submit "Сохранить", class: "btn btn-primary" %>
    
  </p>
  
<% end %> 

<%= link_to 'Назад', root_path%>   
<hr>


<address>
  <strong>Instagram. IoanRog</strong><br>
  Умань. Черкасская обл.<br>
  <abbr title="Phone">P:</abbr> (123) 456-7890
</address>

<address>
  <strong>Почта</strong><br>
  <a href="mailto:#">first.last@example.com</a>
</address>


</div>

app/views/tasks/index.html.erb
<body>
<div class="container">
 <h1>Здравствуй, я твой менеджер задачь!</h1>
 <h3>С чего начнем ?</h3>
  <div class="row">
        <%= form_for @task do |f| %>
            <div class="form-group">
                <%= f.text_field :title, class: "form-control", placeholder: "Название задачи" %>
            </div>

            <div class="form-group">
                <%= f.text_area :text, class: "form-control", size: "40x4", placeholder: "Описание" %>
            </div>
            
            <%= f.submit "Добавить задачу", class: "btn btn-primary" %>
        <% end %>
  </div>
</div>
<hr>
<% @tasks.each do |t| %>
<div class="container">
    <div class="panel panel-success">
      <div class="panel-body">
        <div class="col-md-8">
            <b><%= t.title %></b>
            <p><%= t.text %></p>
            <% if t.status %>
                <p class="text-success">
                    <strong>Задание выполнено.</strong>
                </p>
            <% end %>
        </div>

        <div class="col-md-4">
            <p class="text-right">
                <% unless t.status %>
                <%= link_to done_task_path(t.id), method: :patch  do %>
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                <% end %>
                <% end %>
                <%= link_to edit_task_path(t) do %>
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                <% end %>
                <%= link_to task_path(t), method: :delete, data: { confirm: 'Вы уверены?' } do %>
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                <% end %>
            </p>
        </div>
     
      </div>
    </div>
</div>
</div>
</body>

    
<% end %>